# after created run:
# flutter create .
# flutter pub get
# flutter packages pub run build_runner build --delete-conflicting-outputs

name: my_awesome_app
description: A starting point for flutter applications

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #Provider State Management
  provider: ^4.1.2

  # Servicelocator
  get_it: ^4.0.2
  injectable: ^0.4.0

  # Streaming
  rxdart: ^0.24.1

  # Access Files
  path_provider: ^1.6.8

  # Simle, fast key-value Datatbase
  hive: ^1.4.1+1

  # launch URLs
  url_launcher: ^5.4.7
  url_launcher_platform_interface: ^1.0.7
  url_launcher_web: ^0.1.1+5

  # auto routing using annotations
  auto_route: #^0.5.0
    git:
      url: https://github.com/melewetwo/auto_route_library.git
      ref: issue#113
      path: auto_route

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5
  injectable_generator:
  auto_route_generator: #0.5.0
    git:
     url: https://github.com/melewetwo/auto_route_library.git
     ref: issue#113
     path: auto_route_generator

  # flutter packages pub run build_runner build
  # flutter packages pub run build_runner watch




flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  # Regenerate:
  #   flutter pub get
  #   flutter pub run flutter_launcher_icons:main